{
 "title": "reth - mempool",
 "description": "Metrics for transaction P2P gossip and the local view of mempool data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(reth_info)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Build Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_timestamp}}"
    }
   ]
  },
  {
   "title": "Git SHA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{git_sha}}"
    }
   ]
  },
  {
   "title": "Build Profile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_profile}}"
    }
   ]
  },
  {
   "title": "Target Triple",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{target_triple}}"
    }
   ]
  },
  {
   "title": "Cargo Features",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{cargo_features}}"
    }
   ]
  },
  { "title": "Transaction Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "instance" },
  {
   "title": "TxPool Maintenance",
   "type": "timeseries",
   "description": "Transaction pool maintenance metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_transaction_pool_dirty_accounts{instance=~\"$instance\"}",
     "legendFormat": "Dirty Accounts"
    },
    {
     "expr": "reth_transaction_pool_drift_count{instance=~\"$instance\"}",
     "legendFormat": "Drift Count"
    },
    {
     "expr": "reth_transaction_pool_reinserted_transactions{instance=~\"$instance\"}",
     "legendFormat": "Reinserted Transactions"
    },
    {
     "expr": "reth_transaction_pool_deleted_tracked_finalized_blobs{instance=~\"$instance\"}",
     "legendFormat": "Deleted Tracked Finalized Blobs"
    }
   ]
  },
  {
   "title": "Subpool sizes in bytes",
   "type": "timeseries",
   "description": "Tracks a heuristic of the memory footprint of the various transaction pool sub-pools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_transaction_pool_basefee_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Base fee pool size"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Pending pool size"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Queued pool size"
    },
    {
     "expr": "reth_transaction_pool_blob_pool_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Blob pool size"
    }
   ]
  },
  {
   "title": "Inflight Transaction Requests",
   "type": "timeseries",
   "description": "Currently active outgoing GetPooledTransactions requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "reth_network_inflight_transaction_requests{instance=~\"$instance\"}",
     "legendFormat": "Inflight Transaction Requests"
    }
   ]
  },
  {
   "title": "Subpool transaction count",
   "type": "timeseries",
   "description": "Tracks the number of transactions in the various transaction pool sub-pools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "reth_transaction_pool_basefee_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Base fee pool transactions"
    },
    {
     "expr": "reth_transaction_pool_pending_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Pending pool transactions"
    },
    {
     "expr": "reth_transaction_pool_queued_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Queued pool transactions"
    },
    {
     "expr": "reth_transaction_pool_blob_pool_transactions{instance=~\"$instance\"}",
     "legendFormat": "Blob pool transactions"
    }
   ]
  },
  {
   "title": "Transaction Fetcher Hashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "reth_network_hashes_pending_fetch{instance=~\"$instance\"}",
     "legendFormat": "Hashes in Pending Fetch Cache"
    },
    {
     "expr": "reth_network_hashes_inflight_transaction_requests{instance=~\"$instance\"}",
     "legendFormat": "Hashes in Inflight Requests"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Pending pool imports",
   "type": "timeseries",
   "description": "Number of transactions about to be imported into the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "reth_network_pending_pool_imports{instance=~\"$instance\"}",
     "legendFormat": "Transactions pending import"
    }
   ]
  },
  {
   "title": "Network transaction channel",
   "type": "timeseries",
   "description": "Tracks the number of transaction messages in the channel from the network to the transaction pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(reth_network_pool_transactions_messages_sent{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(reth_network_pool_transactions_messages_received{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Rx"
    },
    {
     "expr": "reth_network_pool_transactions_messages_sent{instance=~\"$instance\"} - reth_network_pool_transactions_messages_received{instance=~\"$instance\"}",
     "legendFormat": "Messages in channel"
    }
   ]
  },
  {
   "title": "Inserted transactions",
   "type": "timeseries",
   "description": "Tracks the number of transactions per second that are inserted and removed from the transaction pool, as well as the number of invalid transactions per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(reth_transaction_pool_inserted_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Inserted transactions"
    },
    {
     "expr": "rate(reth_transaction_pool_removed_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Removed transactions"
    },
    {
     "expr": "rate(reth_transaction_pool_invalid_transactions{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid transactions"
    }
   ]
  },
  {
   "title": "Transactions Manager Poll Duration Nested Function Calls",
   "type": "timeseries",
   "description": "Durations of nested function calls, in one call to poll `TransactionsManager` future:\n\nNetwork Events - stream peer session updates from `NetworkManager`;\nTransaction Events - stream txns gossip from `NetworkManager`;\nPending Transactions - stream hashes of txns successfully inserted into pending set in `TransactionPool`;\nPending Pool Imports - flush txns to pool from `TransactionsManager`;\nFetch Events - stream fetch txn events (success case wraps a tx) from `TransactionFetcher`;\nFetch Pending Hashes - search for hashes announced by an idle peer in cache for hashes pending fetch;\n(Transactions Commands - stream commands from testnet to fetch/serve/propagate txns)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_acc_duration_poll_network_events{instance=\"$instance\"}",
     "legendFormat": "Network Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_transaction_events{instance=\"$instance\"}",
     "legendFormat": "Transaction Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_imported_transactions{instance=\"$instance\"}",
     "legendFormat": "Pending Transactions"
    },
    {
     "expr": "reth_network_acc_duration_poll_pending_pool_imports{instance=\"$instance\"}",
     "legendFormat": "Pending Pool Imports"
    },
    {
     "expr": "reth_network_acc_duration_poll_fetch_events{instance=\"$instance\"}",
     "legendFormat": "Fetch Events"
    },
    {
     "expr": "reth_network_acc_duration_poll_commands{instance=\"$instance\"}",
     "legendFormat": "Commands"
    },
    {
     "expr": "reth_network_acc_duration_fetch_pending_hashes{instance=\"$instance\"}",
     "legendFormat": "Fetch Pending Hashes"
    }
   ]
  },
  {
   "title": "Blob store",
   "type": "timeseries",
   "description": "Tracks the entries, byte size, failed inserts and file deletes of the blob store",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "reth_transaction_pool_blobstore_entries{instance=~\"$instance\"}",
     "legendFormat": "Entries"
    },
    {
     "expr": "reth_transaction_pool_blobstore_byte_size{instance=~\"$instance\"}",
     "legendFormat": "Bytesize"
    },
    {
     "expr": "reth_transaction_pool_blobstore_failed_inserts{instance=~\"$instance\"}",
     "legendFormat": "Failed Inserts"
    },
    {
     "expr": "reth_transaction_pool_blobstore_failed_deletes{instance=~\"$instance\"}",
     "legendFormat": "Failed Deletes"
    }
   ]
  },
  {
   "title": "All Transactions metrics",
   "type": "timeseries",
   "description": "All Transactions metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "reth_transaction_pool_all_transactions_by_hash{instance=~\"$instance\"}",
     "legendFormat": "All transactions by hash"
    },
    {
     "expr": "reth_transaction_pool_all_transactions_by_id{instance=~\"$instance\"}",
     "legendFormat": "All transactions by id"
    },
    {
     "expr": "reth_transaction_pool_all_transactions_by_all_senders{instance=~\"$instance\"}",
     "legendFormat": "All transactions by all senders"
    }
   ]
  },
  {
   "title": "Transactions Manager Future Poll Duration",
   "type": "timeseries",
   "description": "Duration spent inside one call to poll the `TransactionsManager` future",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_duration_poll_tx_manager{instance=\"$instance\"}",
     "legendFormat": "Transactions Manager Future"
    }
   ]
  },
  {
   "title": "Network Manager Future Poll Duration",
   "type": "timeseries",
   "description": "Duration spent inside one call to poll the `NetworkManager` future",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_duration_poll_network_manager{instance=\"$instance\"}",
     "legendFormat": "Network Manager Future"
    }
   ]
  },
  {
   "title": "Network Manager Poll Duration Nested Function Calls",
   "type": "timeseries",
   "description": "Durations of nested function calls, in one call to poll `NetworkManager` future:\n\nNetwork Handle Message - stream network handle messages from `TransactionsManager`;\nSwarm Events - stream transaction gossip from `Swarm`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_network_duration_poll_network_handle{instance=\"$instance\"}",
     "legendFormat": "Network Handle Messages"
    },
    {
     "expr": "reth_network_duration_poll_swarm{instance=\"$instance\"}",
     "legendFormat": "Swarm Events"
    }
   ]
  },
  {
   "title": "Frequency of Transactions Already Marked as Seen by Peer",
   "type": "timeseries",
   "description": "Frequency of a peer sending a transaction that has already been marked as seen by that peer. This could for example be the case if a transaction is sent/announced to the peer at the same time that the peer sends/announces the same transaction to us.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_network_occurrences_hash_already_seen_by_peer{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Freq Announced Transactions Already Seen by Peer"
    },
    {
     "expr": "rate(reth_network_occurrences_of_transaction_already_seen_by_peer{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Freq Received Transactions Already Seen by Peer"
    }
   ]
  },
  {
   "title": "Frequency of Transactions Already in Pool",
   "type": "timeseries",
   "description": "Total number of times a transaction is sent/announced that is already in the local pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_network_occurrences_hashes_already_in_pool{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Freq Announced Transactions Already in Pool"
    },
    {
     "expr": "rate(reth_network_occurrences_transactions_already_in_pool{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Freq Received Transactions Already in Pool "
    }
   ]
  }
 ]
}